/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int MULTI_LINE_COMMENT = 7;
  int ABSTRACT = 8;
  int BOOLEAN = 9;
  int CHAR = 10;
  int CLASS = 11;
  int INTERFACE = 12;
  int ELSE = 13;
  int EXTENDS = 14;
  int IMPLEMENTS = 15;
  int FALSE = 16;
  int IF = 17;
  int IMPORT = 18;
  int INSTANCEOF = 19;
  int INT = 20;
  int NEW = 21;
  int NULL = 22;
  int PACKAGE = 23;
  int PRIVATE = 24;
  int PROTECTED = 25;
  int PUBLIC = 26;
  int RETURN = 27;
  int STATIC = 28;
  int SUPER = 29;
  int THIS = 30;
  int TRUE = 31;
  int VOID = 32;
  int WHILE = 33;
  int PLUS = 34;
  int ASSIGN = 35;
  int DEC = 36;
  int EQUAL = 37;
  int GT = 38;
  int INC = 39;
  int LAND = 40;
  int LE = 41;
  int LNOT = 42;
  int MINUS = 43;
  int PLUS_ASSIGN = 44;
  int MINUS_ASSIGN = 45;
  int STAR_ASSIGN = 46;
  int DIV_ASSIGN = 47;
  int STAR = 48;
  int QUESTION = 49;
  int UCOMP = 50;
  int NEQ = 51;
  int DIV = 52;
  int REM = 53;
  int REM_ASSIGN = 54;
  int DRSHFT = 55;
  int DRSHFT_ASSIGN = 56;
  int TRSHFT = 57;
  int TRSHFT_ASSIGN = 58;
  int GTEQ = 59;
  int DLSHFT = 60;
  int DLSHFT_ASSIGN = 61;
  int LT = 62;
  int HAT = 63;
  int HAT_ASSIGN = 64;
  int BOT = 65;
  int BOT_ASSIGN = 66;
  int LOR = 67;
  int BAND = 68;
  int BAND_ASSIGN = 69;
  int COLON = 70;
  int LPAREN = 71;
  int RPAREN = 72;
  int LCURLY = 73;
  int RCURLY = 74;
  int LBRACK = 75;
  int RBRACK = 76;
  int SEMI = 77;
  int COMMA = 78;
  int DOT = 79;
  int IDENTIFIER = 80;
  int LETTER = 81;
  int DIGIT = 82;
  int NON_ZERO_DIGIT = 83;
  int INT_LITERAL = 84;
  int CHAR_LITERAL = 85;
  int STRING_LITERAL = 86;
  int ESC = 87;
  int ERROR = 88;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"char\"",
    "\"class\"",
    "\"interface\"",
    "\"else\"",
    "\"extends\"",
    "\"implements\"",
    "\"false\"",
    "\"if\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"<=\"",
    "\"!\"",
    "\"-\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"*\"",
    "\"?\"",
    "\"~\"",
    "\"!=\"",
    "\"/\"",
    "\"%\"",
    "\"%=\"",
    "\">>\"",
    "\">>=\"",
    "\">>>\"",
    "\">>>=\"",
    "\">=\"",
    "\"<<\"",
    "\"<<=\"",
    "\"<\"",
    "\"^\"",
    "\"^=\"",
    "\"|\"",
    "\"|=\"",
    "\"||\"",
    "\"&\"",
    "\"&=\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<INT_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
